Working MariaDB 10 version

diff --git a/feeds/packages/utils/mariadb/files/mariadb.init b/feeds/packages/utils/mariadb/files/mariadb.init
--- a/feeds/packages/utils/mariadb/files/mariadb.init
+++ b/feeds/packages/utils/mariadb/files/mariadb.init
@@ -9,22 +9,40 @@ SERVICE_WRITE_PID=1
 SERVICE_STOP_TIME=9
 
 error() {
-	echo "${initscript}:" "$@" 1>&2
+    echo "${initscript}:" "$@" 1>&2
+}
+
+init_command_msg="run mysql_install_db --force --basedir=/usr to initialize the system tables"
+
+missing_dir=0
+
+missing_dir_error() {
+    error "Error: $1 '$2' in /etc/mysql/my.cnf doesn't exist."
+    error "       Make sure that a file system is mounted at this location or you have created the directory"
+    error "       and then $init_command_msg."
+}
+
+check_dir_in_my_cnf() {
+    local dir=$(sed -n -e "s/^[[:space:]]*$1[[:space:]]*=[[:space:]\"']*\([^[:space:]\"']*\)[[:space:]\"']*/\1/p" /etc/mysql/my.cnf)
+    if [ ! -d "$dir" ]; then
+	missing_dir_error $1 $dir
+	missing_dir=1
+    fi
 }
 
 start() {
-	local datadir=$(sed -n -e "s/^[[:space:]]*datadir[[:space:]]*=[[:space:]\"']*\([^[:space:]\"']*\)[[:space:]\"']*/\1/p" /etc/mariadb/my.cnf)
-	if [ ! -d "$datadir" ]; then
-		error "Error: datadir '$datadir' in /etc/mariadb/my.cnf doesn't exist"
-		return 1
-	fi
-	if [ ! -f "$datadir/mysql/tables_priv.MYD" ]; then
-		error "Error: I didn't detect a privileges table, you might need to run mysql_install_db --force --basedir=/usr to initialize the system tables"
-		return 1
-	fi
-	service_start /usr/bin/mariadb
+    check_dir_in_my_cnf datadir
+    check_dir_in_my_cnf tmpdir
+    if [ $missing_dir == 1 ] ; then
+	return 1
+    fi
+    if [ ! -f "$datadir/mysql/tables_priv.MYD" ]; then
+	error "Error: I didn't detect a privileges table, you might need to $init_command_msg"
+	return 1
+    fi
+    service_start /usr/bin/mysqld
 }
 
 stop() {
-	service_stop /usr/bin/mariadb
+    service_stop /usr/bin/mysqld
 }
